config/routes.rb
Rails.application.routes.draw do
  resources :watches

  root 'watches#index'
end

app/models/watch.rb
class Watch < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/watches_controller.rb
class WatchesController < ApplicationController
  before_action :set_watch, only: [:show, :edit, :update, :destroy]

  # GET /watches
  # GET /watches.json
  def index
    @watches = Watch.all
  end

  # GET /watches/1
  # GET /watches/1.json
  def show
  end

  # GET /watches/new
  def new
    @watch = Watch.new
  end

  # GET /watches/1/edit
  def edit
  end

  # POST /watches
  # POST /watches.json
  def create
    @watch = Watch.new(watch_params)

    respond_to do |format|
      if @watch.save
        format.html { redirect_to @watch, notice: 'Watch was successfully created.' }
        format.json { render :show, status: :created, location: @watch }
      else
        format.html { render :new }
        format.json { render json: @watch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /watches/1
  # PATCH/PUT /watches/1.json
  def update
    respond_to do |format|
      if @watch.update(watch_params)
        format.html { redirect_to @watch, notice: 'Watch was successfully updated.' }
        format.json { render :show, status: :ok, location: @watch }
      else
        format.html { render :edit }
        format.json { render json: @watch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /watches/1
  # DELETE /watches/1.json
  def destroy
    @watch.destroy
    respond_to do |format|
      format.html { redirect_to watches_url, notice: 'Watch was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_watch
      @watch = Watch.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def watch_params
      params.require(:watch).permit(:brand, :model, :picture)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/watches_helper.rb
module WatchesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rdf</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/watches/_form.html.erb
<%= form_for(@watch) do |f| %>
  <% if @watch.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@watch.errors.count, "error") %> prohibited this watch from being saved:</h2>

      <ul>
      <% @watch.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :brand %><br>
    <%= f.text_field :brand %>
  </div>
  <div class="field">
    <%= f.label :model %><br>
    <%= f.text_field :model %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.text_field :picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/watches/edit.html.erb
<h1>Editing Watch</h1>

<%= render 'form' %>

<%= link_to 'Show', @watch %> |
<%= link_to 'Back', watches_path %>

app/views/watches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Watches</h1>
<small>Hey ho from docker</small>

<table>
  <thead>
    <tr>
      <th>Brand</th>
      <th>Model</th>
      <th>Picture</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @watches.each do |watch| %>
      <tr>
        <td><%= watch.brand %></td>
        <td><%= watch.model %></td>
        <td><%= watch.picture %></td>
        <td><%= link_to 'Show', watch %></td>
        <td><%= link_to 'Edit', edit_watch_path(watch) %></td>
        <td><%= link_to 'Destroy', watch, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Watch', new_watch_path %>

app/views/watches/new.html.erb
<h1>New Watch</h1>

<%= render 'form' %>

<%= link_to 'Back', watches_path %>

app/views/watches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Brand:</strong>
  <%= @watch.brand %>
</p>

<p>
  <strong>Model:</strong>
  <%= @watch.model %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @watch.picture %>
</p>

<%= link_to 'Edit', edit_watch_path(@watch) %> |
<%= link_to 'Back', watches_path %>